### ISSUE TITLE
relationship with etm-tk

### ISSUE THREAD

**Issue by marczz** [dagraham/etm-dgraham#16]
I just discovered etm, I was previously only knowing etm-tk from the same author. I was wondering how the two projects compare. I guess that etm should be either a rewrite or a fork of etm-tk, but the manual don't even mention etm-tkn either the changes.txt, file I tried to explore the commits, but at some point before importing in github they are only auto-commits.

The name is also confusing the etm package in Debian is etm-tk not etm.

It would be very useful for newcomers like me to add a notice in the Readme with the affiliation of the two projects and comparison on features and dependencies.

Marc

**Comment by dagraham** [comment]
Thanks for you email. I’ll add the connection to the etm README in the next few days. The change from a gui interface based on tk to a terminal based one based on prompt_toolkit with a data store using tiny-db was a complete rewrite, not a fork.  Regarding the name change, etm-prompt_toolkit seemed a bit much. The key packages upon which etm-graham is built include dateutil, pendulum, tinydb and prompt_toolkit. I contributed serializations for dates and datetimes to the tinydb package.

Features. etm-graham (PyPi naming convention), so far as I can remember, supports every feature from etm-tk and more but in a different way. There are fewer reminder types, for instance, but each does more. An event, *,  with a date entry instead of a datetime entry is equivalent to the old all-day event, ^. The action type, ~, is gone but replaced by the ability to add used time entries, @u, to any item type. The common feature is the text-based entry format.

Dan

**Comment by marczz** [comment]
Thank for the detailed answer, concerning the name why not a simple name that differentiate from `etm-tk` like `etm-tui` which indicates that it is a terminal interface and not a gui like the tk app.

The main feature that I don't find in etm (it seems [it is in etm-tk](https://github.com/dagraham/etm-tk/wiki/UserManual#sharing-with-other-calendar-applications))  is ics and vcard export, this would allow to export your appointment and tasks to other applications, (and I want to have my appointments an tasks available on mobile, android or ios) or even to synchronize them to calDAV and cardDARV using vdirsyncer.

Last even I should rather put all this in the discussions thread  as thie is not an *issue*; the manual propose to install with pip or using a venv. For most users it is so simpler to only do:
``` sh
pipx install etm-graham
```
and letting pipx manage virtual environment, and allowing an easy upgrade.

Marc

**Comment by dagraham** [comment]
Thanks for the pipx tip.

I dropped vcal and vcard export because many options in etm were not supported by the standard. Used time entries, for example. Even though supported by the standard, most apps (at the time) didn’t support journal entries. The  “keep_current” and “keep_next” options were intended to provide some mobile support by keeping current.txt and next.txt in the cloud. Any suggestions you might provide about how best to support this would be appreciated.

Dan

**Comment by dagraham** [comment]
The documentation has been updated to describe the history.
